# Generated by Django 5.1.3 on 2024-11-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_classicuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicuser',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
