# Generated by Django 5.2 on 2025-07-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksAndReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
