# Generated by Django 5.2.4 on 2025-07-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_booksandreviews_delete_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksandreviews',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
