# Generated by Django 5.2.4 on 2025-08-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_booksandreviews_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksandreviews',
            name='review',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
